#####################################在yml中配置数据源(HiKariCP)和Mybatis#####################################





######################################################################
#
# 配置数据源信息
#
######################################################################
spring:
  datasource:                                             # 数据源相关配置
    type: com.zaxxer.hikari.HikariDataSource              # 数据源类型：HiKariCP
    driver-class-name: com.mysql.cj.jdbc.Driver           # mysql驱动
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Quxiaowei0419..
    hikari:
      connection-timeout: 30000                           # 等待连接池分配连接的最大时长（毫秒）,超过这个时长还没可用的连接则发生SQLExcepiton，默认30秒
      minimum-idle: 10                                    # 最小连接数（一般最大、最小数值保持一直）
      maximum-pool-size: 10                               # 最大连接数(通常：CPU 4核，size=10；CPU 8核，size=20)
      auto-commit: true                                   # 自动提交
      idle-timeout: 600000                                # 连接超时的最大时长（毫秒）,超时则被释放（retired）,默认10分钟
      pool-name: DataSourceHiKariCP                       # 连接池名字
      max-lifetime: 1800000                               # 连接的生命时长（毫秒）,超时而且没被使用则被释放（retired）,默认：30分钟 1800000ms
      connection-test-query: SELECT 1                     # 连接时测试的语句
    application:
      name: springboot-ssl
